name: CDT_ML
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - tqdm
  - pytorch
  - accelerate
  - torchvision
  - ignite
  - scikit-learn
  - scikit-image


